---
- name: "Check if the Docker Image already exists."
  community.docker.docker_image_info:
    name: "{{ docker_compose.image }}:{{ docker_compose.version }}"
  register: docker_compose_image_build

- name: "Prune Docker builder caches before a build."
  community.docker.docker_prune:
    builder_cache: true
    builder_cache_all: "{{ docker_compose_default_buildx_cache_prune_all | default(false) }}"
  when:
    - docker_compose_image_build.images | length < 1
    - docker_compose.build | default(true)
    - docker_compose_default_buildx_cache_prune | default(true)

- name: "Build the docker image."
  community.docker.docker_image_build:
    name: "{{ docker_compose.image }}"
    path: "{{ docker_compose.basepath | default(docker_compose_default_base_path) }}/{{ docker_compose.name }}"
    args: "{{ docker_compose.build_args | default({}) }}"
    labels: "{{ docker_compose.build_labels | default({}) }}"
    nocache: "{{ docker_compose.build_nocache | default(true) }}"
    outputs: "{{ docker_compose.outputs | default(docker_compose_default_outputs) }}"
    platform: "{{ docker_compose.arch | default(docker_compose_default_archs) }}"
    pull: "{{ docker_compose.build_pull | default(true) }}"
    rebuild: "{{ docker_compose.build_rebuild | default('never') }}"
    tag: "{{ docker_compose.version }}"
  when:
    - docker_compose_image_build.images | length < 1
    - docker_compose.build | default(true)
  notify: "Restart docker_compose."

- name: "Prune Docker builder caches after a build."
  community.docker.docker_prune:
    builder_cache: true
    builder_cache_all: "{{ docker_compose_default_buildx_cache_prune_all | default(false) }}"
  when:
    - docker_compose_image_build.images | length < 1
    - docker_compose.build | default(true)
    - docker_compose_default_buildx_cache_prune | default(true)

- name: "Ensure Docker CLI config directory exists if we have to authenticate."
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.docker"
    state: directory
    mode: "0700"
  when: lookup('ansible.builtin.env', 'DOCKER_AUTH_CONFIG') != ''

- name: "Create Docker CLI auth config from environment variable"
  ansible.builtin.copy:
    content: "{{ lookup('ansible.builtin.env', 'DOCKER_AUTH_CONFIG') }}"
    dest: "{{ ansible_user_dir }}/.docker/config.json"
    mode: '0600'
  when: lookup('ansible.builtin.env', 'DOCKER_AUTH_CONFIG') != ''

- name: "Push the docker image."
  community.docker.docker_image:
    source: local
    name: "{{ docker_compose.image }}"
    tag: "{{ docker_compose.version }}"
    push: true
  when:
    - docker_compose.push | default(false)
...
