---
- name: Check if the Docker Image already exists.
  community.docker.docker_image_info:
    name: "{{ docker_compose.image }}:{{ docker_compose.version }}"
  register: docker_compose_image_build

- name: Build the docker image.
  community.docker.docker_image:
    source: build
    build:
      path: "{{ docker_compose_basepath }}/{{ docker_compose_name }}"
    name: "{{ docker_compose.image }}"
    tag: "{{ docker_compose.version }}"
  when:
    - docker_compose_image_build.images | length < 1
    - docker_compose_build_it
  notify: "Restart docker_compose."
...
