---
- name: "Check if the Docker Image already exists."
  community.docker.docker_image_info:
    name: "{{ docker_compose.image }}:{{ docker_compose.version }}"
  register: docker_compose_image_build

- name: "Build the docker image."
  community.docker.docker_image:
    source: build
    build:
      path: "{{ docker_compose.basepath | default(docker_compose_default_base_path) }}/{{ docker_compose.name }}"
    name: "{{ docker_compose.image }}"
    tag: "{{ docker_compose.version }}"
  when:
    - docker_compose_image_build.images | length < 1
    - docker_compose.build | default(true)
  notify: "Restart docker_compose."

- name: "Push the docker image."
  community.docker.docker_image:
    source: local
    name: "{{ docker_compose.image }}"
    tag: "{{ docker_compose.version }}"
    push: true
  when:
    - docker_compose.push | default(false)
...
