---
- name: "Create container directory."
  ansible.builtin.file:
    name: "{{ docker_compose_container_directory }}"
    state: directory
    mode: "0755"
  loop:
    - "{{ docker_compose.basepath | default(docker_compose_default_base_path) }}"
    - "{{ docker_compose.basepath | default(docker_compose_default_base_path) }}/{{ docker_compose.name }}"
  loop_control:
    loop_var: "docker_compose_container_directory"

- name: "Create additional directories."
  ansible.builtin.file:
    name: "{{ docker_compose.basepath | default(docker_compose_default_base_path) }}/{{ docker_compose.name }}/{{ docker_compose_additional_directory.path }}"
    state: directory
    mode: "{{ docker_compose_additional_directory.mode | default('0755') }}"
    owner: "{{ docker_compose_additional_directory.owner | default(docker_compose_default_build_user) }}"
    group: "{{ docker_compose_additional_directory.group | default(docker_compose_default_build_user) }}"
  loop: "{{ docker_compose_directories }}"
  loop_control:
    loop_var: "docker_compose_additional_directory"
  when:
    - docker_compose_directories is defined
    - docker_compose_directories | length > 0

- name: "Template Dockerfile with default template."
  ansible.builtin.template:
    src: Dockerfile.j2
    dest: "{{ docker_compose.basepath | default(docker_compose_default_base_path) }}/{{ docker_compose.name }}/Dockerfile"
    mode: "0644"
  notify: "Restart docker_compose."
  diff: "{{ docker_compose.debug | default(false) }}"
  when:
    - docker_compose.build | default(true)
    - docker_compose.dockerfile_template | default("") | length < 1
    - docker_compose.dockerfile_file | default("") | length < 1

- name: "Template Dockerfile with custom template."
  ansible.builtin.template:
    src: "{{ docker_compose.dockerfile_template }}"
    dest: "{{ docker_compose.basepath | default(docker_compose_default_base_path) }}/{{ docker_compose.name }}/Dockerfile"
    mode: "0644"
  notify: "Restart docker_compose."
  diff: "{{ docker_compose.debug | default(false) }}"
  when:
    - docker_compose.build | default(true)
    - docker_compose.dockerfile_template | default("") | length > 0

- name: "Copy Dockerfile."
  ansible.builtin.copy:
    src: "{{ docker_compose.dockerfile_file }}"
    dest: "{{ docker_compose.basepath | default(docker_compose_default_base_path) }}/{{ docker_compose.name }}/Dockerfile"
    mode: "0644"
  when:
    - docker_compose.build | default(true)
    - docker_compose.dockerfile_file | default("") | length > 0

- name: "Template docker-compose.yml with default template."
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ docker_compose.basepath | default(docker_compose_default_base_path) }}/{{ docker_compose.name }}/docker-compose.yml"
    mode: "0644"
  notify: "Restart docker_compose."
  diff: "{{ docker_compose.debug | default(false) }}"
  when:
    - docker_compose.compose | default(true)
    - docker_compose.composer_file | default("") | length < 1
    - docker_compose.composer_template | default("") | length < 1

- name: "Template docker-compose.yml with custom template."
  ansible.builtin.template:
    src: "{{ docker_compose.composer_template }}"
    dest: "{{ docker_compose.basepath | default(docker_compose_default_base_path) }}/{{ docker_compose.name }}/docker-compose.yml"
    mode: "0644"
  notify: "Restart docker_compose."
  diff: "{{ docker_compose.debug | default(false) }}"
  when:
    - docker_compose.compose | default(true)
    - docker_compose.composer_template | default("") | length > 0

- name: "Copy docker-compose.yml with custom file."
  ansible.builtin.copy:
    src: "{{ docker_compose.composer_file }}"
    dest: "{{ docker_compose.basepath | default(docker_compose_default_base_path) }}/{{ docker_compose.name }}/docker-compose.yml"
    mode: "0644"
  when:
    - docker_compose.compose | default(true)
    - docker_compose.composer_file | default("") | length > 0

- name: "Copy additional files."
  ansible.builtin.copy:
    src: "{{ docker_compose_copy.src }}"
    dest: "{{ docker_compose.basepath | default(docker_compose_default_base_path) }}/{{ docker_compose.name }}/{{ docker_compose_copy.dest }}"
    mode: "{{ docker_compose_copy.mode | default('0644') }}"
    owner: "{{ docker_compose_copy.owner | default(docker_compose_default_build_user) }}"
    group: "{{ docker_compose_copy.group | default(docker_compose_default_build_user) }}"
  loop: "{{ docker_compose_copies }}"
  loop_control:
    loop_var: "docker_compose_copy"
  when:
    - docker_compose_copies is defined
    - docker_compose_copies | length > 0

- name: "Template files."
  ansible.builtin.template:
    src: "{{ docker_compose_template.src }}"
    dest: "{{ docker_compose.basepath | default(docker_compose_default_base_path) }}/{{ docker_compose.name }}/{{ docker_compose_template.dest }}"
    mode: "{{ docker_compose_template.mode | default('0644') }}"
    owner: "{{ docker_compose_template.owner | default(docker_compose_default_build_user) }}"
    group: "{{ docker_compose_template.group | default(docker_compose_default_build_user) }}"
  loop: "{{ docker_compose_templates }}"
  loop_control:
    loop_var: "docker_compose_template"
  notify: "Restart docker_compose."
  diff: "{{ docker_compose.debug | default(false) }}"
  when:
    - docker_compose_templates is defined
    - docker_compose_templates | length > 0
...
