---
- name: "List all installed Ansible collections"
  ansible.builtin.command:
    cmd: ansible-galaxy collection list
  register: installed_collections
  delegate_to: localhost
  run_once: true
  become: false
  changed_when: false
  when: docker_compose.debug | default(false)

- name: "Display installed collections."
  ansible.builtin.debug:
    msg: "{{ installed_collections.stdout_lines }}"
  run_once: true
  when: docker_compose.debug | default(false)

- name: "Include vars from role."
  ansible.builtin.include_vars:
    file: "{{ include_var_file }}"
  loop: "{{ docker_compose_role_vars }}"
  loop_control:
    loop_var: include_var_file
  when:
    - docker_compose_role_vars is defined
    - docker_compose_role_vars | length > 0

- name: "Show the docker_compose variable if it is not properly included."
  ansible.builtin.debug:
    msg: "{{ docker_compose }}"
  when:
    - docker_compose is undefined
    - docker_compose_role_vars is defined

- name: "Include validation tasks."
  ansible.builtin.include_tasks: validate.yml

- name: "Include cleanup tasks."
  ansible.builtin.include_tasks: cleanup.yml
  when:
    - docker_compose.clean | default(false) or docker_compose.purge | default(false)
    - docker_compose.only_hosts | default([]) | length < 1 or inventory_hostname in docker_compose.only_hosts | default([])
    - docker_compose.not_hosts | default([]) | length < 1 or inventory_hostname not in docker_compose.not_hosts | default([])

- name: "Include config tasks."
  ansible.builtin.include_tasks: config.yml
  when:
    - docker_compose.only_hosts | default([]) | length < 1 or inventory_hostname in docker_compose.only_hosts | default([])
    - docker_compose.not_hosts | default([]) | length < 1 or inventory_hostname not in docker_compose.not_hosts | default([])
    - not docker_compose.purge | default(false)

- name: "Include build tasks."
  ansible.builtin.include_tasks: build.yml
  when:
    - docker_compose.build | default(true)
    - docker_compose.only_hosts | default([]) | length < 1 or inventory_hostname in docker_compose.only_hosts | default([])
    - docker_compose.not_hosts | default([]) | length < 1 or inventory_hostname not in docker_compose.not_hosts | default([])
    - not docker_compose.purge | default(false)

- name: "Include compose tasks."
  ansible.builtin.include_tasks: compose.yml
  when:
    - docker_compose.compose | default(true)
    - docker_compose.only_hosts | default([]) | length < 1 or inventory_hostname in docker_compose.only_hosts | default([])
    - docker_compose.not_hosts | default([]) | length < 1 or inventory_hostname not in docker_compose.not_hosts | default([])
    - not docker_compose.purge | default(false)

- name: "Force a restart if docker_compose.force_restart."
  ansible.builtin.debug:
    msg: "Restart of this container is forced."
  changed_when: true
  notify: "Restart docker_compose."
  when: docker_compose.force_restart | default(false)

# See https://github.com/ansible/ansible/issues/83479
- name: "Register docker_compose_restart_name for proper handler execution with multiple role executions."
  ansible.builtin.set_fact:
    docker_compose_restart_name: "{{ docker_compose.name }}"

- name: "Flush handlers."
  ansible.builtin.meta: flush_handlers

- name: "Execute after scripts."
  ansible.builtin.include_tasks: execute_scripts.yml
  when:
    - docker_compose.execute_scripts is defined
    - docker_compose.execute_scripts | length > 0
    - docker_compose.only_hosts | default([]) | length < 1 or inventory_hostname in docker_compose.only_hosts | default([])
    - docker_compose.not_hosts | default([]) | length < 1 or inventory_hostname not in docker_compose.not_hosts | default([])
    - not docker_compose.purge | default(false)

- name: "Reset all variables for consecutive uses of this role."
  ansible.builtin.set_fact:
    docker_compose: []
    docker_compose_builds: []
    docker_compose_build: []
    docker_compose_services: []
    docker_compose_directories: []
    docker_compose_extdirs: []
    docker_compose_templates: []
    docker_compose_copies: []
    docker_compose_volumes: []
    docker_compose_networks: []
    docker_compose_configs: []
    docker_compose_secrets: []
    docker_compose_role_vars: []
...
