---
- name: Check role parameters.
  ansible.builtin.assert:
    that:
      - docker_compose_name is defined
      - docker_compose is defined
    fail_msg: "You have to define docker_compose_name and the docker_compose variable structure."

- name: Check configuration.
  ansible.builtin.assert:
    that:
      - docker_compose.image is defined
      - docker_compose.version is defined
    fail_msg: "Missing mandatory parameter (image or version) in: {{ docker_compose }}"

- name: Show element we are working on.
  ansible.builtin.debug:
    msg: "{{ docker_compose }}"
  when: docker_compose_debug_it
...
