---
- name: "Show all elements we are working on."
  ansible.builtin.debug:
    msg: "{{ docker_compose_element }}"
  loop:
    - "docker_compose: {{ docker_compose }}"
    - "docker_compose_build: {{ docker_compose_build | default([]) }}"
    - "docker_compose_builds: {{ docker_compose_builds }}"
    - "docker_compose_templates: {{ docker_compose_templates | default([]) }}"
    - "docker_compose_directories: {{ docker_compose_directories | default([]) }}"
    - "docker_compose_services: {{ docker_compose_services | default([]) }}"
    - "docker_compose_copies: {{ docker_compose_copies | default([]) }}"
    - "docker_compose_volumes: {{ docker_compose_volumes | default([]) }}"
    - "docker_compose_networks: {{ docker_compose_networks | default([]) }}"
    - "docker_compose_configs: {{ docker_compose_configs | default([]) }}"
    - "docker_compose_secrets: {{ docker_compose_secrets | default([]) }}"
    - "docker_compose_role_vars: {{ docker_compose_role_vars | default([]) }}"
  loop_control:
    loop_var: docker_compose_element
  when: docker_compose.debug | default(false)
  no_log: not docker_compose.debug | default(false) | bool

- name: "Check role parameters."
  ansible.builtin.assert:
    that:
      - docker_compose is defined
      - docker_compose_builds is defined
      - docker_compose_builds | length > 0
    fail_msg: "You have to define at least the docker_compose and docker_compose_builds variables properly."

- name: "Check docker_compose configuration."
  ansible.builtin.assert:
    that:
      - docker_compose.name is defined
      - docker_compose.image is defined
      - docker_compose.version is defined
    fail_msg: "Missing mandatory elements in docker_compose"

- name: "Check docker_compose_builds configuration."
  ansible.builtin.assert:
    that:
      - docker_compose_build_element.from is defined
    fail_msg: "Missing mandatory element 'from' in all docker_compose_builds elements"
  loop: "{{ docker_compose_builds }}"
  loop_control:
    loop_var: docker_compose_build_element
...
