---
- name: "Some hack to install python and ca-certificates on debian containers."
  hosts: all
  gather_facts: false
  tasks:
    - name: "Find out what OS we are on"
      ansible.builtin.raw: cat /etc/issue
      register: molecule_os_issue
    - name: "Install python3 and ca-certificates"
      ansible.builtin.raw: "apt-get update && apt-get install -y python3 ca-certificates"
      when: '"Kernel" not in molecule_os_issue.stdout'
- name: Converge
  hosts: all
  vars:
    docker_compose:
      name: "test"
      image: "test"
      version: 1
      build: false
      debug: true
      compose: false
    docker_compose_builds:
      - from: "debian:trixie-20250721-slim"
    docker_compose_build: []
    docker_compose_directories:
      - path: "foo"
    docker_compose_extdirs:
      - path: "/mnt/bar"
  tasks:
    - ansible.builtin.import_role:
        name: "{{ lookup('env', 'PROJECT_DIR') }}"
    - name: "Pause for Molecule Inspection."
      ansible.builtin.pause:
...
