{# FIRST THE REPEATABLE STUFF #}
{% if docker_compose_builds is defined %}
{% if docker_compose_builds | length > 0 %}
{% for build in docker_compose_builds %}
{% if build.args_before is defined %}
{% if build.args_before | length > 0 %}
{% for arg_before in build.args_before %}
ARG {{ arg_before }}
{% endfor %}{% endif %}{% endif %}
{# HERE WE FORCE docker_compose_build.from TO EXIST #}
FROM {{ build.from | default("") }}
{% if build.args_after is defined %}
{% if build.args_after | length > 0 %}
{% for arg_after in build.args_after %}
ARG {{ arg_after }}
{% endfor %}{% endif %}{% endif %}
{% if build.adds is defined %}
{% if build.adds | length > 0 %}
{% for add in build.adds %}
ADD {{ add }}
{% endfor %}{% endif %}{% endif %}
{% if build.copies is defined %}
{% if build.copies | length > 0 %}
{% for copy in build.copies %}
COPY {{ copy }}
{% endfor %}{% endif %}{% endif %}
{% if build.envs is defined %}
{% if build.envs | length > 0 %}
{% for env in build.envs %}
ENV {{ env }}
{% endfor %}{% endif %}{% endif %}
{% if build.runs is defined %}
{% if build.runs | length > 0 %}
RUN echo "Building Image" && \
{% for run_step in build.runs %}
    {{ run_step }}{% if not loop.last %} && \{% endif +%}
{% endfor %}{% endif %}{% endif %}
{% endfor %}{% endif %}{% endif %}

{# AND THEN THE UNIQUE STUFF #}
{% if docker_compose_build.volumes is defined %}
{% if docker_compose_build.volumes | length > 0 %}
VOLUME [{% for volume in docker_compose_build.volumes %}"{{ volume }}"{% if not loop.last %}, {% endif %}{% endfor %}]
{% endif %}{% endif %}
{% if docker_compose_build.entrypoints is defined %}
{% if docker_compose_build.entrypoints | length > 0 %}
ENTRYPOINT [{% for entrypoint in docker_compose_build.entrypoints %}"{{ entrypoint }}"{% if not loop.last %}, {% endif %}{% endfor %}]
{% endif %}{% endif %}
{% if docker_compose_build.cmds is defined %}
{% if docker_compose_build.cmds | length > 0 %}
CMD [{% for cmd in docker_compose_build.cmds %}"{{ cmd }}"{% if not loop.last %}, {% endif %}{% endfor %}]
{% endif %}{% endif %}
{% if docker_compose_build.exposes is defined %}
{% if docker_compose_build.exposes | length > 0 %}
{% for expose in docker_compose_build.exposes %}
EXPOSE {{ expose }}
{% endfor %}{% endif %}{% endif %}
{% if docker_compose_build.healthcheck is defined %}
{% if docker_compose_build.healthcheck | length > 0 %}
HEALTHCHECK {{ docker_compose_build.healthcheck }}
{% endif %}{% endif %}
USER {{ docker_compose_build.user | default("root") }}
WORKDIR {{ docker_compose_build.workdir | default("/") }}
{% if docker_compose_build.shell is defined %}
SHELL {{ docker_compose_build.shell | default('["/bin/sh", "-c"]') }}
{% endif %}
STOPSIGNAL {{ docker_compose_build.stopsignal | default('SIGTERM') }}
{% if docker_compose_build.labels is defined %}
{% if docker_compose_build.labels | length > 0 %}
LABEL {% for label in docker_compose_build.labels %}{{ label }}{% if not loop.last %} {% endif %}{% endfor %}
{% endif %}{% endif %}
